export const GET_PARTS = "REQUEST/GET/PARTS"; 
export const GET_FORUM = "REQUEST/GET/FORUM"; 
export const GET_TOPIC = "REQUEST/GET/TOPIC"; 
export const GET_SENDERS = "REQUEST/GET/SENDERS"; 
export const GET_MESSAGES = "REQUEST/GET/MESSAGES"; 
export const GET_NOTICES = "REQUEST/GET/NOTICES";
export const GET_PROFILE = "REQUEST/GET/PROFILE";
export const GET_USER_DATA = "REQUEST/GET/USER_DATA";
export const GET_PARTSLIST = "REQUEST/GET/PARTSLIST";
export const GET_SUBSCRIBES = "REQUEST/GET/SUBSCRIBES";

export const CREATE_PART = "REQUEST/CREATE/PART";
export const CREATE_FORUM = "REQUEST/CREATE/FORUM";
export const CREATE_TOPIC = "REQUEST/CREATE/TOPIC";
export const CREATE_POST = "REQUEST/CREATE/POST";
export const CREATE_MESSAGE = "REQUEST/CREATE/MESSAGE";
export const CREATE_SUBSCRIBE = "REQUEST/CREATE/SUBSCRIBE";
export const CREATE_USER_DATA = "REQUEST/CREATE/USER_DATA";

export const CHANGE_PART = "REQUEST/CHANGE/PART";
export const CHANGE_FORUM = "REQUEST/CHANGE/FORUM";
export const CHANGE_TOPIC = "REQUEST/CHANGE/TOPIC";
export const CHANGE_POST = "REQUEST/CHANGE/POST";
export const CHANGE_NOTICES = "REQUEST/CHANGE/NOTICES";
export const CHANGE_USER_DATA = "REQUEST/CHANGE/USER_DATA";

export const DELETE_FORUM = "REQUEST/DELETE/FORUM";
export const DELETE_TOPIC = "REQUEST/DELETE/TOPIC";
export const DELETE_POST = "REQUEST/DELETE/POST";
export const DELETE_SUBSCRIBE = "REQUEST/DELETE/SUBSCRIBE";
export const DELETE_ACCOUNT = "REQUEST/DELETE/ACCOUNT";

export const SET_PARTS = "RESPONSE/SET_PARTS"; 
export const SET_FORUM = "RESPONSE/SET_FORUM"; 
export const SET_TOPIC = "RESPONSE/SET_TOPIC"; 
export const SET_SENDERS = "RESPONSE/SET_SENDERS"; 
export const SET_MESSAGES = "RESPONSE/SET_MESSAGES"; 
export const SET_NOTICES = "RESPONSE/SET_NOTICES";
export const SET_PROFILE = "RESPONSE/SET_PROFILE";
export const SET_USER_DATA = "RESPONSE/SET_USER_DATA";
export const SET_GUEST_DATA = "RESPONSE/SET_GUEST_DATA";
export const SET_PARTSLIST = "RESPONSE/SET_PARTSLIST";
export const SET_SUBSCRIBES = "RESPONSE/SET_SUBSCRIBES";

export const RETURN_TOPIC = "FORUMPAGE/RETURN_TOPIC";
export const ADD_DELETED_TOPIC = "FORUMPAGE/ADD_DELETED_TOPIC";

export const RETURN_POST = "TOPICPAGE/RETURN_POST";
export const ADD_DELETED_POST = "TOPICPAGE/ADD_DELETED_POST";

export const SHOW_ALERT = "POPUP/SHOW_ALERT";
export const HIDE_ALERT = "POPUP/HIDE_ALERT";
export const SHOW_REDACTOR = "POPUP/SHOW_REDACTOR";
export const HIDE_REDACTOR = "POPUP/HIDE_REDACTOR";
export const SHOW_PROMPT = "POPUP/SHOW_PROMPT";
export const HIDE_PROMPT = "POPUP/HIDE_PROMPT";
export const SHOW_PROFILE = "POPUP/SHOW_PROFILE";
export const HIDE_PROFILE = "POPUP/HIDE_PROFILE";
export const SHOW_MESSAGER = "POPUP/SHOW_MESSAGER";
export const HIDE_MESSAGER = "POPUP/HIDE_MESSAGER";

export const RENDER_USER = "MESSAGER/RENDER_USER";

