export const GET_PARTS = "REQUEST/GET/PARTS"; 
export const GET_FORUM = "REQUEST/GET/FORUM"; 
export const GET_TOPIC = "REQUEST/GET/TOPIC"; 
export const GET_SENDERS = "REQUEST/GET/SENDERS"; 
export const GET_MESSAGES = "REQUEST/GET/MESSAGES"; 
export const GET_NOTICES = "REQUEST/GET/NOTICES";
export const GET_PROFILE = "REQUEST/GET/PROFILE";
export const GET_PARTSLIST = "REQUEST/GET/PARTSLIST";
export const GET_SUBSCRIBES = "REQUEST/GET/SUBSCRIBES";
export const CONFIRM_MAIL = "REQUEST/GET/CONFIRM_MAIL";
export const GET_MAILING = "REQUEST/GET/MAILING";
export const GET_IGNORED = "REQUEST/GET/IGNORED";

export const CREATE_PART = "REQUEST/CREATE/PART";
export const CREATE_FORUM = "REQUEST/CREATE/FORUM";
export const CREATE_TOPIC = "REQUEST/CREATE/TOPIC";
export const CREATE_POST = "REQUEST/CREATE/POST";
export const CREATE_MESSAGE = "REQUEST/CREATE/MESSAGE";
export const CREATE_SUBSCRIBE = "REQUEST/CREATE/SUBSCRIBE";
export const CREATE_IGNORED = "REQUEST/CREATE/IGNORED";
export const CREATE_USER_DATA = "REQUEST/CREATE/USER_DATA";
export const CREATE_USER_AUTHENTICATION = "REQUEST/CREATE/USER_AUTHENTICATION";

export const CHANGE_PART = "REQUEST/CHANGE/PART";
export const CHANGE_FORUM = "REQUEST/CHANGE/FORUM";
export const CHANGE_TOPIC = "REQUEST/CHANGE/TOPIC";
export const CHANGE_POST = "REQUEST/CHANGE/POST";
export const CHANGE_NOTICES = "REQUEST/CHANGE/NOTICES";
export const CHANGE_USER_DATA = "REQUEST/CHANGE/USER_DATA";
export const CHANGE_MESSAGER_SETTINGS = "REQUEST/CHANGE/MESSAGER_SETTINGS";

export const DELETE_FORUM = "REQUEST/DELETE/FORUM";
export const DELETE_TOPIC = "REQUEST/DELETE/TOPIC";
export const DELETE_POST = "REQUEST/DELETE/POST";
export const DELETE_SUBSCRIBE = "REQUEST/DELETE/SUBSCRIBE";
export const DELETE_ACCOUNT = "REQUEST/DELETE/ACCOUNT";
export const DELETE_IGNORED = "REQUEST/DELETE/IGNORED";

export const SET_PARTS = "RESPONSE/SET_PARTS"; 
export const SET_FORUM = "RESPONSE/SET_FORUM"; 
export const SET_TOPIC = "RESPONSE/SET_TOPIC"; 
export const SET_SENDERS = "RESPONSE/SET_SENDERS"; 
export const SET_MESSAGES = "RESPONSE/SET_MESSAGES"; 
export const SET_NOTICES = "RESPONSE/SET_NOTICES";
export const SET_PROFILE = "RESPONSE/SET_PROFILE";
export const SET_USER_DATA = "RESPONSE/SET_USER_DATA";
export const SET_GUEST_DATA = "RESPONSE/SET_GUEST_DATA";
export const SET_PARTSLIST = "RESPONSE/SET_PARTSLIST";
export const SET_SUBSCRIBES = "RESPONSE/SET_SUBSCRIBES";
export const SET_MAILING = "RESPONSE/SET_MAILING";
export const SET_IGNORED = "RESPONSE/SET_IGNORED";

export const RETURN_TOPIC = "FORUMPAGE/RETURN_TOPIC";
export const ADD_DELETED_TOPIC = "FORUMPAGE/ADD_DELETED_TOPIC";

export const RETURN_POST = "TOPICPAGE/RETURN_POST";
export const ADD_DELETED_POST = "TOPICPAGE/ADD_DELETED_POST";

export const SHOW_ALERT = "POPUP/SHOW_ALERT";
export const HIDE_ALERT = "POPUP/HIDE_ALERT";
export const SHOW_REDACTOR = "POPUP/SHOW_REDACTOR";
export const HIDE_REDACTOR = "POPUP/HIDE_REDACTOR";
export const SHOW_PROMPT = "POPUP/SHOW_PROMPT";
export const HIDE_PROMPT = "POPUP/HIDE_PROMPT";
export const SHOW_PROFILE = "POPUP/SHOW_PROFILE";
export const HIDE_PROFILE = "POPUP/HIDE_PROFILE";
export const SHOW_MESSAGER = "POPUP/SHOW_MESSAGER";
export const HIDE_MESSAGER = "POPUP/HIDE_MESSAGER";

export const RENDER_USER = "MESSAGER/RENDER_USER";

export const SHOW_SECTION = "SETTINGS/SHOW_SECTION";

export const SHOW_PARTS_LOADING = "LOADING/SHOW_PARTS_LOADING";
export const SHOW_FORUM_LOADING = "LOADING/SHOW_FORUM_LOADING";
export const SHOW_TOPIC_LOADING = "LOADING/SHOW_TOPIC_LOADING";
export const SHOW_SENDERS_LOADING = "LOADING/SHOW_SENDERS_LOADING";
export const SHOW_MESSAGES_LOADING = "LOADING/SHOW_MESSAGES_LOADING";
export const SHOW_NOTICES_LOADING = "LOADING/SHOW_NOTICES_LOADING";
export const SHOW_SUBSCRIBES_LOADING = "LOADING/SHOW_SUBSCRIBES_LOADING";
export const SHOW_IGNORED_LOADING = "LOADING/SHOW_IGNORED_LOADING";
export const SHOW_PROFILE_LOADING = "LOADING/SHOW_PROFILE_LOADING";
export const SHOW_USER_LOADING = "LOADING/SHOW_USER_LOADING";
export const SHOW_MAILING_LOADING = "LOADING/SHOW_MAILING_LOADING";

export const CLOSE_PARTS_LOADING = "LOADING/CLOSE_PARTS_LOADING";
export const CLOSE_FORUM_LOADING = "LOADING/CLOSE_FORUM_LOADING";
export const CLOSE_TOPIC_LOADING = "LOADING/CLOSE_TOPIC_LOADING";
export const CLOSE_SENDERS_LOADING = "LOADING/CLOSE_SENDERS_LOADING";
export const CLOSE_MESSAGES_LOADING = "LOADING/CLOSE_MESSAGES_LOADING";
export const CLOSE_NOTICES_LOADING = "LOADING/CLOSE_NOTICES_LOADING";
export const CLOSE_SUBSCRIBES_LOADING = "LOADING/CLOSE_SUBSCRIBES_LOADING";
export const CLOSE_IGNORED_LOADING = "LOADING/CLOSE_IGNORED_LOADING";
export const CLOSE_PROFILE_LOADING = "LOADING/CLOSE_PROFILE_LOADING";
export const CLOSE_USER_LOADING = "LOADING/CLOSE_USER_LOADING";
export const CLOSE_MAILING_LOADING = "LOADING/CLOSE_MAILING_LOADING";

